name: Sync to Service Repo

on:
  push:
    branches:
      - dev

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          path: source-repo

      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: Shadownc/CYI-Service
          token: ${{ secrets.PAT_TOKEN }}
          path: target-repo

      - name: Get commit message
        id: get_commit_message
        run: |
          cd source-repo
          echo "message=$(git log -1 --format=%s)" >> $GITHUB_OUTPUT

      - name: Sync files
        run: |
          mkdir -p target-repo/front
          rm -rf target-repo/front/*
          # 使用 cp -a 来复制所有文件，包括隐藏文件
          cp -a source-repo/. target-repo/front/
          cd target-repo
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          # 检查是否有改动
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          else
            git commit -m "sync(front): ${{ steps.get_commit_message.outputs.message }}"
            git push origin main
          fi
