name = "cyi-workers"
type = "module"
main = "src/index.js"
compatibility_date = "2024-09-20"

# 绑定 D1 数据库
[[d1_databases]]
binding = "CYI_IMGDB"
database_name = "testimg"
database_id = "c9a4248c-9587-4d61-a069-adf6613d828e"

# 绑定 KV 命名空间
[[kv_namespaces]]
binding = "CYI_IMGKV"
id = "e41adceae7984bb683676248cf14acfd"

[vars]
JWT_SECRET = "aaa"