name: Build Release Assets

on:
  release:
    types: [created]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build Frontend
        run: |
          cd front
          npm install
          npm run build
          cd dist
          zip -r ../../frontend.zip .
          echo "✅ Frontend build completed"

      - name: Build Worker
        run: |
          cd service
          npm install
          npx wrangler deploy --dry-run --outdir=dist
          mv dist/index.js ../worker.js
          echo "✅ Worker build completed"

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            frontend.zip
            worker.js
          tag_name: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
